import sys
import time

def callMe(name, number):
    print("Microsoft Tech Support: Hello my friend")
    time.sleep(2)
    print("Karen: Hello? Who's this?")
    time.sleep(2)
    print("Microsoft Tech Support: I am "+ name)
    time.sleep(2)
    print("Karen: Hi "+ name + " so why'd you call me exactly?")
    time.sleep(2)
    print("Microsoft Tech Support: Your computer has virus.")
    time.sleep(2)
    print("Karen: Oh no! How can I fix that?")
    time.sleep(2)
    print("Microsoft Tech Support: Ok before we start can you please give phone number?")
    time.sleep(2)
    print("Karen: Yes, my phone number is " + number)
    time.sleep(2)
    print("Microsoft Tech Support: Ok can you please download AnyDesk.")
    time.sleep(2)
    print("Karen: Okay I downloaded it, what now?")
    time.sleep(2)
    print("Microsoft Tech Support: Ok now please log into your bank account.")
    time.sleep(2)
    print("Karen: Why would I need to log into my bank-")
    time.sleep(1)
    print("Microsoft Tech Support: JUST DO IT WOMAN OR I WILL KILL YOUR FAMILY")
    time.sleep(2)
    print("Karen: Okay okay fine, please don't kill my family.")
    time.sleep(2)
    print("Microsoft Tech Support: Okay so now I refund you money...")
    time.sleep(2)
    print("Microsoft Tech Support: OH NO I SENT YOU TOO MUCH MONEY PLEASE REFUND ME OR MY BOSS WILL FIRE ME AND I CAN'T FEED MY FAMILY")
    time.sleep(2)
    print("Karen: How do u want me to refund u?")
    time.sleep(2)
    print("Microsoft Tech Support: Please give me 2000$ in Google Play Store Gift Card.")
    time.sleep(2)
    print("Karen: Uh. Okay... I'll go to Target to buy-")
    time.sleep(1)
    print("Karen's Son: WHAT ARE YOU DOING MOM YOU'RE OBVIOUSLY GETTING SCAMMED!")
    time.sleep(1)
    print("Karen: But this guy can't feed his-")
    time.sleep(1)
    print("*Hangs up*...")

callMe(sys.argv[1], sys.argv[2])